id: I01A3A373
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T20:26:47+00:00'
last_modified: '2022-06-08T01:21:31.109128+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG3554
  title: དབུ་མ་རྩ་བ་ཤེས་རབ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4444':
      image_group_id: I1KG3624
      title: ''
      total_pages: 106
      order: 1
      base_file: 4444.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
